### ISSUE TITLE
Formatting error in README tables

### ISSUE THREAD

**Issue by ColMcp** [asweigart/humre#2]
This looks to be an interesting and useful project -- thanks for creating it!

I have noticed that the "Regex Equivalent" columns of the README tables are mal-formatted whenever the regex contains pipe characters. I think the pipes need to be escaped.

**Comment by ColMcp** [comment]
This seems to be a 'feature' of the GitHub and PyPI markdown processors. Using a different processor, `mkdocs`, pipe characters within backticks in tables are treated as normal characters not column delimiters.

**Comment by asweigart** [comment]
Fixed in 0.2.0. Thanks!
